name = "photography-learning"
compatibility_date = "2025-06-13"
main = "worker/src/index.ts"

[site]
bucket = "./out"

[build]
command = "npm run build"

[assets]
directory = "./out"

[[routes]]
pattern = "photographystudy.online/*"
zone_name = "photographystudy.online"

[[routes]]
pattern = "www.photographystudy.online/*"
zone_name = "photographystudy.online" 