name = "photography-learning"
main = "src/index.ts"
compatibility_date = "2023-10-30"

[site]
bucket = "../out"

[build]
command = "cd .. && npm run build"

[env.production]
name = "photography-learning-prod"
route = "photography-learning.yourdomain.com/*" 